version: 2

project_name: voxclip

before:
  hooks:
    - go mod tidy

builds:
  - id: voxclip
    main: ./cmd/voxclip
    binary: voxclip
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/fmueller/voxclip/internal/version.Version={{ .Version }}
      - -X github.com/fmueller/voxclip/internal/version.Commit={{ .Commit }}
      - -X github.com/fmueller/voxclip/internal/version.Date={{ .Date }}

archives:
  - id: voxclip
    ids:
      - voxclip
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: packaging/whisper/{{ .Os }}_{{ .Arch }}/whisper-cli
        dst: libexec/whisper/whisper-cli
      - src: LICENSE
        dst: LICENSE
      - src: README.md
        dst: README.md
      - src: THIRD_PARTY_NOTICES.md
        dst: THIRD_PARTY_NOTICES.md

checksum:
  name_template: checksums.txt

changelog:
  use: git

brews:
  - name: voxclip
    ids:
      - voxclip
    repository:
      owner: fmueller
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/fmueller/voxclip"
    description: "Voice capture and transcription CLI — record, transcribe, and copy to clipboard locally"
    license: "MIT"
    skip_upload: auto
    dependencies:
      - name: ffmpeg
        os: mac
    install: |
      bin.install "voxclip"
      (libexec/"whisper").mkpath
      (libexec/"whisper").install "libexec/whisper/whisper-cli"
    test: |
      system bin/"voxclip", "--version"
